site_name: Onepanel Documentation
site_url: https://docs.onepanel.io
site_author: Onepanel, Inc.
repo_url: https://github.com/onepanelio/docs
theme:
  name: 'material'
  logo: assets/img/onepanel-logo-white.svg
extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js
nav:
  - About Onepanel: index.md
  - Get Started:
    - Core Concepts: core-concepts.md
  - CLI:
    - 'Getting started with CLI': cli/index.md
  - SDK:
    - 'Getting started with SDK': sdk/index.md
  - Environments:
    - List of Environments: environments/index.md
  - Machine Types:
    - List of Machine Types: machine-types/index.md
  - Volume Types:
    - List of Volume Types: volume-types/index.md
markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    # - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        permalink: true