site_name: Onepanel Documentation
site_url: https://docs.onepanel.io
site_author: Onepanel, Inc.
site_description: Extensible machine learning and deep learning platform on GPUs
repo_url: https://github.com/onepanelio/docs
theme:
  name: 'material'
  logo: assets/img/onepanel-logo-white.svg
  favicon: assets/img/favicon.png
extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js
nav:
  - About Onepanel: index.md
  - Get Started:
    - Core Concepts: start/core-concepts.md
    - Onepanel CLI: start/cli.md
    - Onepanel SDK: start/sdk.md
  - Projects:
    - Overview: projects/index.md
    - Create a New Project: projects/create.md
    - Delete a Project: projects/delete.md
    - Manage Repositories: projects/repositories.md
  - Workspaces:
    - Overview: workspaces/index.md
    - Create a Workspace: workspaces/create.md
    - Pause and Resume: workspaces/pause-resume.md
    - Switch Machine Types: workspaces/machine-types.md
  - Jobs:
    - Overview: jobs/index.md
  - Datasets:
    - Overview: datasets/index.md
    - Create: datasets/create.md
    - Mount a Dataset: datasets/mount.md
  - CLI:
    - Overview: cli/index.md
    - Job Commands: cli/job-commands.md
  - SDK:
    - Overview: sdk/index.md
  - Integrations:
    - Access Tokens: integrations/access-tokens.md
    - Environment Variables: integrations/environment-variables.md
    - Git Credentials: integrations/git-credentials.md
  - Environments:
    - List of Environments: environments/index.md
    - Custom Packages: environments/custom-packages.md
  - Machine Types:
    - List of Machine Types: machine-types/index.md
    - Spot Instances: machine-types/spot.md
  - Volume Types:
    - List of Volume Types: volume-types/index.md
markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    # - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        permalink: true