site_name: Onepanel Documentation
site_url: https://docs.onepanel.io
site_author: Onepanel, Inc.
repo_url: https://github.com/onepanelio/docs
theme:
  name: 'material'
  logo: assets/img/onepanel-logo-white.svg
  palette:
    primary: 'indigo'
extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js
nav:
  - Home: index.md
  - CLI:
    - 'Getting started with CLI': cli/index.md
  - SDK:
    - 'Getting started with SDK': sdk/index.md
markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde