site_name: Onepanel Documentation
site_url: https://docs.onepanel.io
site_author: Onepanel, Inc.
repo_url: https://github.com/onepanelio/docs
theme:
  name: 'material'
pages:
  - Home: index.md
  - CLI:
    - 'Getting started with CLI': cli/index.md
  - SDK:
    - 'Getting start with SDK': sdk/index.md
