site_name: Onepanel Documentation
site_url: https://docs.onepanel.io
site_author: Onepanel, Inc.
site_description: Extensible machine learning and deep learning platform on GPUs
repo_url: https://github.com/onepanelio/docs
theme:
  name: 'material'
  logo: assets/img/onepanel-logo-white.svg
  favicon: assets/img/favicon.png
copyright: Copyright &copy; 2019 Onepanel, Inc.
extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js
extra:
  social:
    - type: 'github'
      link: 'https://github.com/onepanelio'
    - type: 'slack'
      link: 'https://join.slack.com/t/onepanel-users/shared_invite/enQtNTI3Mzc1OTEzMjY0LTBjMDMxM2E4NTUxZTVmMjU0OTYzYzRjZDY4Y2ViZDE5Yzc5YzkzZDI4MDg3ZThhZmEyMjlhOWM1NzVkOGY4MzI'
    - type: 'twitter'
      link: 'https://twitter.com/onepanelio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/onepanelio'
    - type: 'facebook'
      link: 'https://facebook.com/onepanelio'
nav:
  - About Onepanel: index.md
  - Get Started:
    - Core concepts: start/core-concepts.md
    - Onepanel CLI: start/cli.md
    - Onepanel SDK: start/sdk.md
  - Projects:
    - Overview: projects/index.md
    - Create a new project: projects/create.md
    - Fork a project: projects/forking.md
    - Manage members: projects/members.md
    - Manage repositories: projects/repositories.md
    - Delete a project: projects/delete.md
  - Workspaces:
    - Overview: workspaces/index.md
    - Create a workspace: workspaces/create.md
    - Workspace interactions: workspaces/interactions.md
    - Switch machine types: workspaces/machine-types.md
    - Pause and resume: workspaces/pause-resume.md
    - Delete a workspace: workspaces/delete.md
  - Jobs:
    - Overview: jobs/index.md
  - Datasets:
    - Overview: datasets/index.md
    - Create: datasets/create.md
    - Mount a dataset: datasets/mount.md
  - CLI:
    - Overview: cli/index.md
    - onepanel login: cli/login.md
    - onepanel logout: cli/logout.md
    - onepanel projects: cli/projects.md
    - onepanel datasets: cli/datasets.md
    - onepanel jobs: cli/jobs.md
    - onepanel download: cli/download.md
    - onepanel environments: cli/environments.md
    - onepanel machine-types: cli/machine-types.md
    - onepanel volume-types: cli/volume-types.md
  - SDK:
    - Overview: sdk/index.md
  - Integrations:
    - Access tokens: integrations/access-tokens.md
    - Environment variables: integrations/environment-variables.md
    - Git credentials: integrations/git-credentials.md
  - Environments:
    - List of environments: environments/index.md
    - Custom packages: environments/custom-packages.md
  - Machine Types:
    - List of machine types: machine-types/index.md
    - Spot machines: machine-types/spot.md
  - Volume Types:
    - List of volume types: volume-types/index.md
markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    # - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        permalink: true