name: CI

on:
  push:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: install mkdocs
      run: |
        pip install wheel
        pip install mkdocs
        pip install mkdocs-material
    - name: build mkdocs
      run: |
        mkdocs build
    - name: deploy to github pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: site    
    
